/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubstitutionRouteImport } from './routes/substitution'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LineupRouteImport } from './routes/lineup'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayersIndexRouteImport } from './routes/players.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PlayersIdRouteImport } from './routes/players.$id'
import { Route as AdminTeamsRouteImport } from './routes/admin.teams'
import { Route as AdminSeasonsRouteImport } from './routes/admin.seasons'
import { Route as AdminRostersRouteImport } from './routes/admin.rosters'
import { Route as AdminRecordsRouteImport } from './routes/admin.records'
import { Route as AdminPlayersRouteImport } from './routes/admin.players'
import { Route as AdminMatchesRouteImport } from './routes/admin.matches'

const SubstitutionRoute = SubstitutionRouteImport.update({
  id: '/substitution',
  path: '/substitution',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LineupRoute = LineupRouteImport.update({
  id: '/lineup',
  path: '/lineup',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PlayersIdRoute = PlayersIdRouteImport.update({
  id: '/players/$id',
  path: '/players/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamsRoute = AdminTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeasonsRoute = AdminSeasonsRouteImport.update({
  id: '/seasons',
  path: '/seasons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRostersRoute = AdminRostersRouteImport.update({
  id: '/rosters',
  path: '/rosters',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecordsRoute = AdminRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlayersRoute = AdminPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMatchesRoute = AdminMatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/compare': typeof CompareRoute
  '/leaderboard': typeof LeaderboardRoute
  '/lineup': typeof LineupRoute
  '/login': typeof LoginRoute
  '/substitution': typeof SubstitutionRoute
  '/admin/matches': typeof AdminMatchesRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/records': typeof AdminRecordsRoute
  '/admin/rosters': typeof AdminRostersRoute
  '/admin/seasons': typeof AdminSeasonsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/players/$id': typeof PlayersIdRoute
  '/admin/': typeof AdminIndexRoute
  '/players/': typeof PlayersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/compare': typeof CompareRoute
  '/leaderboard': typeof LeaderboardRoute
  '/lineup': typeof LineupRoute
  '/login': typeof LoginRoute
  '/substitution': typeof SubstitutionRoute
  '/admin/matches': typeof AdminMatchesRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/records': typeof AdminRecordsRoute
  '/admin/rosters': typeof AdminRostersRoute
  '/admin/seasons': typeof AdminSeasonsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/players/$id': typeof PlayersIdRoute
  '/admin': typeof AdminIndexRoute
  '/players': typeof PlayersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/compare': typeof CompareRoute
  '/leaderboard': typeof LeaderboardRoute
  '/lineup': typeof LineupRoute
  '/login': typeof LoginRoute
  '/substitution': typeof SubstitutionRoute
  '/admin/matches': typeof AdminMatchesRoute
  '/admin/players': typeof AdminPlayersRoute
  '/admin/records': typeof AdminRecordsRoute
  '/admin/rosters': typeof AdminRostersRoute
  '/admin/seasons': typeof AdminSeasonsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/players/$id': typeof PlayersIdRoute
  '/admin/': typeof AdminIndexRoute
  '/players/': typeof PlayersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/compare'
    | '/leaderboard'
    | '/lineup'
    | '/login'
    | '/substitution'
    | '/admin/matches'
    | '/admin/players'
    | '/admin/records'
    | '/admin/rosters'
    | '/admin/seasons'
    | '/admin/teams'
    | '/players/$id'
    | '/admin/'
    | '/players/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/compare'
    | '/leaderboard'
    | '/lineup'
    | '/login'
    | '/substitution'
    | '/admin/matches'
    | '/admin/players'
    | '/admin/records'
    | '/admin/rosters'
    | '/admin/seasons'
    | '/admin/teams'
    | '/players/$id'
    | '/admin'
    | '/players'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/compare'
    | '/leaderboard'
    | '/lineup'
    | '/login'
    | '/substitution'
    | '/admin/matches'
    | '/admin/players'
    | '/admin/records'
    | '/admin/rosters'
    | '/admin/seasons'
    | '/admin/teams'
    | '/players/$id'
    | '/admin/'
    | '/players/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CompareRoute: typeof CompareRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LineupRoute: typeof LineupRoute
  LoginRoute: typeof LoginRoute
  SubstitutionRoute: typeof SubstitutionRoute
  PlayersIdRoute: typeof PlayersIdRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/substitution': {
      id: '/substitution'
      path: '/substitution'
      fullPath: '/substitution'
      preLoaderRoute: typeof SubstitutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lineup': {
      id: '/lineup'
      path: '/lineup'
      fullPath: '/lineup'
      preLoaderRoute: typeof LineupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/': {
      id: '/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/players/$id': {
      id: '/players/$id'
      path: '/players/$id'
      fullPath: '/players/$id'
      preLoaderRoute: typeof PlayersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teams': {
      id: '/admin/teams'
      path: '/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminTeamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seasons': {
      id: '/admin/seasons'
      path: '/seasons'
      fullPath: '/admin/seasons'
      preLoaderRoute: typeof AdminSeasonsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rosters': {
      id: '/admin/rosters'
      path: '/rosters'
      fullPath: '/admin/rosters'
      preLoaderRoute: typeof AdminRostersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/records': {
      id: '/admin/records'
      path: '/records'
      fullPath: '/admin/records'
      preLoaderRoute: typeof AdminRecordsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/players': {
      id: '/admin/players'
      path: '/players'
      fullPath: '/admin/players'
      preLoaderRoute: typeof AdminPlayersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/matches': {
      id: '/admin/matches'
      path: '/matches'
      fullPath: '/admin/matches'
      preLoaderRoute: typeof AdminMatchesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminMatchesRoute: typeof AdminMatchesRoute
  AdminPlayersRoute: typeof AdminPlayersRoute
  AdminRecordsRoute: typeof AdminRecordsRoute
  AdminRostersRoute: typeof AdminRostersRoute
  AdminSeasonsRoute: typeof AdminSeasonsRoute
  AdminTeamsRoute: typeof AdminTeamsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminMatchesRoute: AdminMatchesRoute,
  AdminPlayersRoute: AdminPlayersRoute,
  AdminRecordsRoute: AdminRecordsRoute,
  AdminRostersRoute: AdminRostersRoute,
  AdminSeasonsRoute: AdminSeasonsRoute,
  AdminTeamsRoute: AdminTeamsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CompareRoute: CompareRoute,
  LeaderboardRoute: LeaderboardRoute,
  LineupRoute: LineupRoute,
  LoginRoute: LoginRoute,
  SubstitutionRoute: SubstitutionRoute,
  PlayersIdRoute: PlayersIdRoute,
  PlayersIndexRoute: PlayersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
